### ISSUE TITLE
Facing issue for rollbar in penetrating test

### ISSUE THREAD

**Issue by Gautam-zodape** [rollbar/rollbar-apple#131]
I have run the penetrating security test on the iOS app found issue with Rollbar library.
pen test error : The binary may contain the following insecure API(s).

Following are the classes which used insecure api methods-
vsnprintf 
1. KSFileUtil : Line number 368
2.  KSLogger : Line number 132
3. KSObjC : Line number 421

stat
1. KSFileUtil : Line number 159

following is the list of other insecure method usage in rollbar - 
_memcpy , _vsnprintf , _stat , _strncat , _strcpy , _printf , _strlen , _sscanf , _sprintf , _fopen , _strcat , _chmod , _strncpy

Could you provide alternate solution for it?

**Comment by akornich** [comment]
@Gautam-zodape , thanks for letting us know. However, the issue seems to be specifically KSCrash related (that is a library used by our RollbarKSCrash module). 

Please, report the issue to [KSCrash repo](https://github.com/kstenerud/KSCrash). We will update our dependency as soon as they have a fix for this.

You can use our RollbarPLCrashReporter module as an alternative. It does not rely on KSCrash and uses [PLCrashReporter](https://github.com/microsoft/plcrashreporter) library for the crash reporting purposes instead of KSCrash.
Also, both modules, RollbarCrash and RollbarPLCrashReporter, are optional in case you already have some other alternative for crash reporting specifically.

**Comment by akornich** [comment]
closing due to no replies
